# Название канала (используется в плейсхолдерах)
name: 'Стандартный'
# Режим работы канала
# DEFAULT - стандартный режим работы (просто телепортирует на рандомные координаты)
# NEAR_PLAYER - телепортирует игрока рядом с другими игроками (/rtp player проще говоря)
# NEAR_REGION - телепортирует игрока рядом с регионом worldguard (/rtp base проще говоря)
type: DEFAULT
# Миры в которых действует канал
# Если игрок телепортируется по данному каналу в одном из этих миров - телепорт будет именно в этом мире
active_worlds:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
# Должен ли канал телепортировать игрока в тот мир, который будет первым в списке active_worlds
# в случае если игрок пытается телепортироваться через него из другого мира? (полезно в случае, если канал должен вызываться из мира спавна например)
teleport_to_first_world: true
# На какой сервер в сети будет перемещать канал, если режим proxy включён
# Имена берутся из конфигурации прокси, однако в основном конфиге плагина также должны быть указаны корректные названия!
# Если указано '' или же режим proxy не включён - то это не будет иметь эффекта
server_to_move: ''
# Сколько игроков должно быть на сервере, чтобы по каналу можно было телепортироваться? (-1 чтобы отключить)
min_players_to_use: -1
# Сколько тиков игрок должен быть неуязвим после телепортации через канал RTP (-1 чтобы отключить)
invulnerable_after_teleport: 15
# Разрешить ли телепортироваться по каналу при помощи команды?
allow_in_command: true
# Разрешить ли обходить лимитёр максимального числа телепортов для этого канала?
# Может быть полезно для каналов со спецификацией void, чтобы игроки всегда могли телепортироваться по ним
bypass_max_teleport_limit: false
# Какая заготовка будет использована для дальнейших настроек канала? (Указывается в templates.yml)
# Используется, если какая-либо настройка не указывается в канале на прямую, но должна в нём присутствовать
# Если указано '' - то это не будет иметь эффекта
template: ''
# Отдельные спецификации канала
specifications:
  # Телепортировать ли игрока на РТП при первом входе?
  teleport_on_first_join: false
  # Из каких миров должна работать телепортация на РТП из пустоты.
  # Полезно использовать если нужен телепорт после падения в яму
  # Если указано [] - не будет телепортировать при падении в пустоту
  void_worlds: []
  # Уровень пустоты. Если игрок опустится на данную высоту и void_worlds не пуст - он будет телепортирован.
  # Если не указан - используется ванильное значение уровня пустоты для вашей версии. (0/-60)
  void_level: 0
  # Из каких миров должна работать телепортация на РТП при респавне.
  # Принцип работы тот же, как у void_worlds
  respawn_worlds: []
# Настройка цены телепортации по данному каналу
costs:
  # Тип используемой валюты
  # VAULT - будет использован vault api (предполагает наличие менеджера экономики, по типу EssentialsX или CMI)
  # PLAYERPOINTS - будет использован апи плагина PlayerPoints
  money_type: VAULT
  # Цена телепортации в монетах (-1 чтобы отключить)
  money_cost: -1
  # Цена телепортации в единицах голода
  hunger_cost: -1
  # Цена телепортации в единицах очков опыта
  experience_cost: -1
# Принцип выбора локации
location_generation_options:
  # Форма заготовки для поиска локации
  # SQUARE - прямоугольник. При нем min_x/z и max_x/z являются 2мя противоположными сторонами прямоугольника
  # ROUND - круг. При нем min_x/z и max_x/z являются 2мя противоположными сторонами прямоугольника, через который будет построен круг (или овал), вписывающийся в данный прямоугольник
  shape: SQUARE
  # Фрмат генерации локации
  # RECTANGULAR - мы строим одну геометрическую фигуру для генерации локации (строится фигура между max_x/z и min_x/z в зависимости от shape)
  # RADIAL - строятся геометрические 2 фигуры, между которыми создаётся зона телепортации (строятся фигуры с максимальным max_x/z и минимальным min_x/z радиусами от center_x/z)
  gen_format: RECTANGULAR
  # Координаты
  min_x: -1000
  max_x: 1000
  min_z: -1000
  max_z: 1000
  # Координаты при работе с форматом генерации RADIAL
  center_x: 0
  center_z: 0
  # Координаты при работе с NEAR_<ЧТО-ТО>
  # Какое может быть самое близкое и самое далёкое расстояние от точки локации исходного объекта
  min_near_point_distance: 30
  max_near_point_distance: 60
  # Максимальное кол-во попыток найти локацию для телепорта (нужно, чтобы не застрять в бесконечном цикле поиска локации)
  max_location_attempts: 50
# Настройки кулдаунов
cooldown:
  # Дефолтный кулдаун для телепортации (-1 чтобы отключить)
  default_cooldown: 60
  # Кулдауны на телепортации в секундах для каждой группы (Поставьте {} чтобы отключить кулдауны для групп вообще, -1 чтобы отключить кулдаун для группы)
  # Для корректной работы выставьте в конфиге LuckPerms vault-group-use-displaynames: false
  group_cooldowns:
    vip: 30
    premium: 10
  # Кулдаун до телепортации (-1 чтобы отключить)
  default_pre_teleport_cooldown: 5
  # Кулдауны до телепортации в секундах для каждой группы (Поставьте {} чтобы отключить кулдауны для групп вообще, -1 чтобы отключить кулдаун для группы)
  pre_teleport_group_cooldowns:
    vip: 1
  # Если группа игрока не указана в списке, то будет браться кулдаун для самой последней группы из списка, вместо дефолтного
  use_last_group_cooldown: false
# Настройка боссбара обратного отсчета
# Не активен, если кулдаун до телепортации < 0
bossbar:
  # Включен ли боссбар
  enabled: true
  # Настройки боссбара
  # Доступные цвета боссбара: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
  # Доступные стили боссбара: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
  title: '&fТелепортация через: &5%time%'
  color: WHITE
  style: SEGMENTED_12
  # Должен ли прогресс боссбара быть плавным?
  smooth_progress: false
# Настройка партиклов
particles:
  # Настройка анимации до телепорта
  # Не активна, если кулдаун до телепортации < 0
  pre_teleport:
    # Включены ли партиклы
    enabled: false
    # Анимация на выбор: BASIC, CAGE
    animation: BASIC
    # Нужно ли отправлять партиклы только игроку, который телепортируется?
    send_only_to_player: true
    # Какие будут партиклы в анимации
    # Будут по порядку
    id:
      - FLAME
    # Сколько будет изначальных точек отсчета для анимации
    # Для BASIC - обозначает кол-во летающих вокруг игрока точек
    # Для CAGE - обозначает кол-во точек окружности клетки
    dots: 16
    # Сколько будет линий анимации (используется только для CAGE)
    lines: 8
    # Сколько будет точек в линии анимации (используется только для CAGE)
    dots_per_line: 8
    # Как будут располагаться основные круги у клетки (используется только для CAGE)
    # Указывается сверху вниз
    circles_offset:
      - '2.0'
      - '0.0'
    # На каком расстоянии от игрока будут появляться партиклы
    radius: 1.25
    # Как быстро должны разлетаться партиклы (0.0 чтобы они были статичными)
    particle_speed: 0.0
    # Какова будет скорость анимации
    speed: 4.0
    # Должна ли анимация быть инвертированной
    # Против часовой, а не по часовой и не сверху вниз, а снизу вверх (в случае если jumping: false)
    invert: false
    # Должна ли анимация быть "прыгающей"
    jumping: true
    # Должна ли анимация приближаться к игроку? (invert не применяется к данному параметру)
    move_near: true
  # Настройка партиклов после телепорта
  after_teleport:
    # Включены ли партиклы
    enabled: true
    # Нужно ли отправлять партиклы только игроку, который телепортируется?
    send_only_to_player: true
    # Какой будет партикл
    id: CLOUD
    # Сколько их будет
    count: 45
    # На каком расстоянии от игрока будут появляться партиклы
    radius: 1.25
    # Как быстро должны разлетаться партиклы (0.0 чтобы они были статичными)
    particle_speed: 0.0
# Запреты, которые накладываются на игрока перед телепортацией
# Не активны, если кулдаун до телепортации < 0
restrictions:
  # Запрет движения до рандомного телепорта
  move: true
  # Запрет телепортации до рандомного телепорта (учитывается любой телепорт кроме плагинов)
  teleport: true
  # Запрет получения урона до рандомного телепорта
  damage: true
  # Запрет нанесения урона другим существам
  damage_others: false
  # Если эта функция включена - проверка урона будет применяться только если урон был причинен одним игроком другому
  damage_check_only_players: true
# Различные исключения телепортации
avoid:
  # Блоки на которе игрока нельзя/можно будет телепортировать
  # Чтобы отключить проверку - поставьте list: []
  blocks:
    # Режим работы.
    # true - на эти блоки нельзя телепортировать false - можно телепортировать только на эти блоки
    blacklist: true
    list:
      - 'LAVA'
      - 'WATER'
  # Биомы в которых игрока нельзя/можно будет телепортировать
  # Чтобы отключить проверку - поставьте list: []
  biomes:
    # Режим работы.
    # true - в эти биомы нельзя телепортировать false - можно телепортировать только в эти биомы
    blacklist: true
    list:
      - 'OCEAN'
  # Блокировать ли телепортацию игрока в регионы WorldGuard
  regions: true
  # Блокировать ли телепортацию игрока в города Towny
  towns: false
# Действия при телепортации
# Доступные действия:
# [MESSAGE] <сообщение> - отправить сообщение игроку (поддерживает PlaceholderAPI, если включён)
# [ACTIONBAR] <сообщение> - отправить сообщение игроку в экшн-бар
# [SOUND] <id>;<громкость>;<тон> - отправить звук игроку
# [TITLE] <тайтл>;<субтайтл>;<время_появления>;<время_показа>;<время_пропадания> - отправить тайтл игроку
# [EFFECT] <эффект>;<время>;<уровень> - выдать эффект игроку
# [CONSOLE] <команда> - выполнить команду от консоли
# [PLAYER] <команда> - выполнить команду от имени игрока (команда указывается без '/')
actions:
  # Формат хекса - &#IIIDDD
  # Доступные плейсхолдеры
  # %player% - ник игрока
  # %name% - имя канала телепортации
  # %time% - время до телепортации
  # %x% %y% %z% - координаты локации
  # Для [MESSAGE] доступен ховертекст и клик-ивент. Указывать через hoverText={Текст-при-наведении} и clickEvent={айди-действия;действие-при-клике}
  # Доступные действия для clickEvent: https://www.javadoc.io/static/net.kyori/adventure-api/4.17.0/net/kyori/adventure/text/event/ClickEvent.Action.html
  # Также для [MESSAGE] доступны кнопки. Создаются при помощи button={Текст-кнопки;Действие1;Действие2}. Действия 1 и 2 - hoverText и clickEvent соответственно.
  pre_teleport:
    - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7&l) &6» &fВы будете телепортированы через %time% Не двигайтесь и не получайте урона. &6(Отменить РТП - /rtp cancel)'
    - '[SOUND] BLOCK_NOTE_BLOCK_PLING;1;1'
  on_cooldown:
    3:
      - '[TITLE] &aТелепорт через &e3...;&r;5;50;10'
    2:
      - '[TITLE] &aТелепорт через &62...;&r;5;50;10'
    1:
      - '[TITLE] &aТелепорт через &c1...;&r;5;50;10'
  after_teleport:
    - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7&l) &6» &aУспешная телепортация! &fВы телепортировались на координаты: &2%x% %y% %z%.'
    - '[TITLE] &a&lУспех!;&fВы телепортировались на координаты: &2%x% %y% %z%.'
    - '[SOUND] ENTITY_PLAYER_LEVELUP;1;1'